version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./api:/app
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    ports:
      - "8080:8080"
    tty: true

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - "api"
